# Generated by Django 3.1.6 on 2021-03-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=260)),
                ('pwd', models.CharField(max_length=50)),
            ],
        ),
    ]
