# Generated by Django 3.1.6 on 2021-04-01 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0003_auto_20210326_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='profilepicture/')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_app.logindummy')),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
