# Generated by Django 3.1.6 on 2021-04-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0004_auto_20210401_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pic', models.FileField(upload_to='files/')),
            ],
        ),
    ]
