# Generated by Django 3.1.6 on 2021-04-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0005_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
