# Generated by Django 3.1.6 on 2021-04-02 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0006_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='dob',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='role',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fb_app.role'),
            preserve_default=False,
        ),
    ]
