# Generated by Django 3.1.6 on 2021-04-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0007_auto_20210402_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
